import { Carta } from '../modelos/carta.model';
import { Colecao } from '../modelos/colecao.model';
import { Pedido } from '../modelos/pedido.model';
import { Produto } from '../modelos/produto.model';
import { UsuarioAdmin } from '../modelos/usuario.model';

const IMAGEM_TESTE_CARD = 'assets/img/TESTE-CARD.jpg';
const IMAGEM_TESTE_BOX = 'assets/img/TESTE-BOX.png';
const IMAGEM_TESTE_FIGURE = 'assets/img/TESTE-FIGURE.png';
const IMAGEM_TESTE_PELUCIA = 'assets/img/TESTE-PELUCIA.png';

export const FIXTURES_CARTAS: Carta[] = [
  {
    id: 9101,
    nome: 'Dragon Nova GX',
    descricao: 'Carta promocional com arte cosmica para destaque na home e no catalogo.',
    preco: 89.9,
    raridade: 'SR',
    tipo: 'Fogo',
    conjunto: 'Nebula Ascendente',
    conjuntoId: 801,
    imagemUrl: IMAGEM_TESTE_CARD,
    quantidadeEstoque: 6,
    numero: '015/100',
    codigoColecao: 'NA',
    artista: 'Studio Kai',
    hp: 220,
    destaque: true,
  },
  {
    id: 9102,
    nome: 'Aqua Sentinel',
    descricao: 'Carta de agua com arte oceanica e presenca marcante em campo.',
    preco: 54.5,
    raridade: 'AR',
    tipo: 'Agua',
    conjunto: 'Mares do Amanhecer',
    conjuntoId: 802,
    imagemUrl: IMAGEM_TESTE_CARD,
    quantidadeEstoque: 12,
    numero: '021/078',
    codigoColecao: 'MA',
    artista: 'Lumen Forge',
    hp: 180,
    destaque: true,
  },
  {
    id: 9103,
    nome: 'Verdant Pulse',
    descricao: 'Carta de planta voltada para estrategias de suporte e controle.',
    preco: 22.9,
    raridade: 'U',
    tipo: 'Planta',
    conjunto: 'Floresta Prisma',
    conjuntoId: 803,
    imagemUrl: IMAGEM_TESTE_CARD,
    quantidadeEstoque: 20,
    numero: '007/064',
    codigoColecao: 'FP',
    artista: 'Aster Lab',
    hp: 120,
    destaque: false,
  },
  {
    id: 9104,
    nome: 'Circuit Lynx',
    descricao: 'Carta eletrica de ritmo rapido para compor linhas ofensivas.',
    preco: 31.75,
    raridade: 'R',
    tipo: 'Eletrico',
    conjunto: 'Cidade Cobalto',
    conjuntoId: 804,
    imagemUrl: IMAGEM_TESTE_CARD,
    quantidadeEstoque: 14,
    numero: '031/090',
    codigoColecao: 'CC',
    artista: 'North Arc',
    hp: 140,
    destaque: true,
  },
  {
    id: 9105,
    nome: 'Shadow Rift',
    descricao: 'Carta sombria com presenca tatica e faixa de preco intermediaria.',
    preco: 64,
    raridade: 'RR',
    tipo: 'Sombrio',
    conjunto: 'Nebula Ascendente',
    conjuntoId: 801,
    imagemUrl: IMAGEM_TESTE_CARD,
    quantidadeEstoque: 8,
    numero: '048/100',
    codigoColecao: 'NA',
    artista: 'Hex Room',
    hp: 190,
    destaque: false,
  },
  {
    id: 9106,
    nome: 'Aurora Shell',
    descricao: 'Carta defensiva com preco de entrada e boa resistencia em campo.',
    preco: 18.4,
    raridade: 'C',
    tipo: 'Agua',
    conjunto: 'Mares do Amanhecer',
    conjuntoId: 802,
    imagemUrl: IMAGEM_TESTE_CARD,
    quantidadeEstoque: 30,
    numero: '004/078',
    codigoColecao: 'MA',
    artista: 'Blue Echo',
    hp: 90,
    destaque: false,
  },
  {
    id: 9107,
    nome: 'Iron Colossus',
    descricao: 'Carta metalica com valor alto para enriquecer cards de destaque.',
    preco: 129.9,
    raridade: 'UR',
    tipo: 'Metal',
    conjunto: 'Cidade Cobalto',
    conjuntoId: 804,
    imagemUrl: IMAGEM_TESTE_CARD,
    quantidadeEstoque: 4,
    numero: '077/090',
    codigoColecao: 'CC',
    artista: 'Forge Unit',
    hp: 260,
    destaque: true,
  },
  {
    id: 9108,
    nome: 'Bloom Scribe',
    descricao: 'Carta de suporte com foco em consistencia e vantagem de recursos.',
    preco: 27.3,
    raridade: 'R',
    tipo: 'Planta',
    conjunto: 'Floresta Prisma',
    conjuntoId: 803,
    imagemUrl: IMAGEM_TESTE_CARD,
    quantidadeEstoque: 11,
    numero: '026/064',
    codigoColecao: 'FP',
    artista: 'Green Relay',
    hp: 110,
    destaque: false,
  },
];

export const FIXTURES_COLECOES: Colecao[] = [
  {
    id: 801,
    nome: 'Nebula Ascendente',
    descricao: 'Colecao com criaturas cosmicas e cartas de alto impacto visual.',
    imagemUrl: IMAGEM_TESTE_BOX,
    logoUrl: IMAGEM_TESTE_BOX,
    dataLancamento: '2025-11-10',
    totalCartas: 2,
    serie: 'Horizonte Galactico',
  },
  {
    id: 802,
    nome: 'Mares do Amanhecer',
    descricao: 'Colecao de ritmo leve com foco em cartas de agua e suporte.',
    imagemUrl: IMAGEM_TESTE_BOX,
    logoUrl: IMAGEM_TESTE_BOX,
    dataLancamento: '2025-08-02',
    totalCartas: 2,
    serie: 'Cronicas Oceano',
  },
  {
    id: 803,
    nome: 'Floresta Prisma',
    descricao: 'Colecao focada em tipos naturais e cartas de suporte.',
    imagemUrl: IMAGEM_TESTE_BOX,
    logoUrl: IMAGEM_TESTE_BOX,
    dataLancamento: '2025-05-18',
    totalCartas: 2,
    serie: 'Raizes Eternas',
  },
  {
    id: 804,
    nome: 'Cidade Cobalto',
    descricao: 'Colecao de linha futurista com criaturas mecanizadas e energia intensa.',
    imagemUrl: IMAGEM_TESTE_BOX,
    logoUrl: IMAGEM_TESTE_BOX,
    dataLancamento: '2026-01-21',
    totalCartas: 2,
    serie: 'Tecnologia Urbana',
  },
];

export const FIXTURES_PRODUTOS: Produto[] = [
  {
    id: 9201,
    nome: 'Figure Dragon Nova',
    descricao: 'Action figure premium inspirada em Dragon Nova GX.',
    preco: 249.9,
    categoria: 'figura',
    imagemUrl: IMAGEM_TESTE_FIGURE,
    quantidadeEstoque: 5,
    destaque: true,
  },
  {
    id: 9202,
    nome: 'Pelucia Aqua Sentinel',
    descricao: 'Pelucia inspirada em Aqua Sentinel para a vitrine de colecionaveis.',
    preco: 129.5,
    categoria: 'pelucia',
    imagemUrl: IMAGEM_TESTE_PELUCIA,
    quantidadeEstoque: 9,
    destaque: false,
  },
  {
    id: 9203,
    nome: 'Box Nebula Ascendente',
    descricao: 'Box promocional com itens da colecao Nebula Ascendente.',
    preco: 319.9,
    categoria: 'box',
    imagemUrl: IMAGEM_TESTE_BOX,
    quantidadeEstoque: 7,
    destaque: true,
  },
  {
    id: 9204,
    nome: 'Deck Shield Carbon',
    descricao: 'Acessorio com acabamento texturizado para proteger o deck.',
    preco: 39.9,
    categoria: 'acessorio',
    imagemUrl: IMAGEM_TESTE_BOX,
    quantidadeEstoque: 25,
    destaque: false,
  },
  {
    id: 9205,
    nome: 'Figure Iron Colossus',
    descricao: 'Figure de acabamento metalico voltada a colecionadores premium.',
    preco: 289,
    categoria: 'figura',
    imagemUrl: IMAGEM_TESTE_FIGURE,
    quantidadeEstoque: 3,
    destaque: true,
  },
  {
    id: 9206,
    nome: 'Pelucia Bloom Scribe',
    descricao: 'Pelucia usada para manter a secao de presentes mais diversa.',
    preco: 99.9,
    categoria: 'pelucia',
    imagemUrl: IMAGEM_TESTE_PELUCIA,
    quantidadeEstoque: 12,
    destaque: false,
  },
];

export const FIXTURES_PEDIDOS: Pedido[] = [
  {
    id: 9301,
    usuarioId: 999,
    nomeCliente: 'Ana Martins',
    emailCliente: 'ana.martins@triade.com.br',
    itens: [
      {
        id: 1,
        cartaId: 9101,
        nomeProduto: 'Dragon Nova GX',
        imagemUrl: IMAGEM_TESTE_CARD,
        quantidade: 1,
        precoUnitario: 89.9,
      },
      {
        id: 2,
        produtoId: 9204,
        nomeProduto: 'Deck Shield Carbon',
        imagemUrl: IMAGEM_TESTE_BOX,
        quantidade: 2,
        precoUnitario: 39.9,
      },
    ],
    status: 'enviado',
    total: 169.7,
    formaPagamento: 'PIX',
    enderecoEntrega: {
      cep: '01001-000',
      logradouro: 'Rua das Colecoes',
      numero: '15',
      bairro: 'Centro',
      cidade: 'Sao Paulo',
      uf: 'SP',
    },
    dataCriacao: '2026-03-28T14:20:00.000Z',
    dataAtualizacao: '2026-03-29T09:10:00.000Z',
  },
  {
    id: 9302,
    usuarioId: 999,
    nomeCliente: 'Ana Martins',
    emailCliente: 'ana.martins@triade.com.br',
    itens: [
      {
        id: 1,
        produtoId: 9203,
        nomeProduto: 'Box Nebula Ascendente',
        imagemUrl: IMAGEM_TESTE_BOX,
        quantidade: 1,
        precoUnitario: 319.9,
      },
    ],
    status: 'entregue',
    total: 319.9,
    formaPagamento: 'Cartao',
    enderecoEntrega: {
      cep: '30140-071',
      logradouro: 'Avenida Aurora',
      numero: '240',
      complemento: 'Apto 1204',
      bairro: 'Funcionarios',
      cidade: 'Belo Horizonte',
      uf: 'MG',
    },
    dataCriacao: '2026-02-16T11:45:00.000Z',
    dataAtualizacao: '2026-02-21T18:00:00.000Z',
  },
];

export const FIXTURES_USUARIOS: UsuarioAdmin[] = [
  {
    id: 1,
    nome: 'Thiago Almeida',
    email: 'thiago.almeida@triade.com.br',
    ativo: true,
    dataCadastro: '2026-01-02T09:00:00.000Z',
    perfil: 'desenvolvedor',
    observacao: 'Perfil com acesso total para manutencao, identidade visual e configuracoes globais.',
    ultimoAcesso: '2026-04-08T10:15:00.000Z',
  },
  {
    id: 2,
    nome: 'Marina Admin',
    email: 'marina.costa@triade.com.br',
    ativo: true,
    dataCadastro: '2026-01-08T09:30:00.000Z',
    perfil: 'administrador',
    observacao: 'Pode operar o painel inteiro, exceto funcoes exclusivas de desenvolvedor.',
    ultimoAcesso: '2026-04-08T09:30:00.000Z',
  },
  {
    id: 3,
    nome: 'Pedro Conteudo',
    email: 'pedro.conteudo@triade.com.br',
    ativo: true,
    dataCadastro: '2025-12-14T15:10:00.000Z',
    perfil: 'mantenedor',
    observacao: 'Perfil focado em cadastro e manutencao operacional sem poder de exclusao.',
    ultimoAcesso: '2026-04-07T18:10:00.000Z',
  },
];